[connection]
brokers = ["aiokafka://localhost:9092"]
use_ssl = false

[connection.ssl]
ca_file = "/path/to/ca.pem"
server_verification_required = true
client_cert_file = "/path/to/client_certificate.pem"
client_key_file = "/path/to/client_key.pem"
client_key_password = "password for the private key"
check_hostname = true

[rdap_dn]
app_id = "domrad-rdap-dn"
debug = false
# The number of worker threads that process input entries
concurrency = 4

# RDAP request timeout (seconds)
http_timeout = 5
# Allow max `limiter_concurrency` requests in `limiter_window` seconds
# for a single RDAP endpoint.
limiter_concurrency = 5
limiter_window = 60

[rdap_ip]
app_id = "domrad-rdap-ip"
debug = false

# RDAP request timeout (seconds)
http_timeout = 5

[rtt]
app_id = "domrad-rtt"
debug = false

ping_count = 5
privileged_mode = false

[zone]
app_id = "domrad-zone"
debug = false

dns_servers = ["195.113.144.194", "195.113.144.233"]
timeout = 5
rotate_nameservers = false

[extractor]
app_id = "domrad-extractor"
data_dir = "/path/to/data"

[classifier-unit]
app_id = "domrad-classifier-unit"
